### ISSUE TITLE
Recuperar as matérias do usuário à partir do RA

### ISSUE THREAD

**Issue by abacchi00** [TatuZap/ETLTatuZap#7]
Isso pode ser feito via um comando no terminal, por exemplo: `recuperar 11201810247`

## 🔧 Tasks
- [x] Inicializar projeto com as bibliotecas necessárias 
  - Info: feita no PR #8 
- [x] Consultar e baixar tabelas/planilhas que vamos consumir numa primeira versão
  - Info: foi mergeado direto na main
- [x] Implementar o raspador
  - Info: Conteudo na branch dev-tratamento-dataframes
- [x] Implementar a 'query' que pega os dados no objeto raspado
  - Info: Em andamento, esperando conserto do tratamento dos dataframes para dar sequência a task no PR #9 
- [x] Colocar tecnologias que vamos usar e como rodar o comando implementado do README
  - Info: feita nos PRS #11 e #9

**Comment by joaomendonca30** [comment]
1º Task - Inicializar projeto com as bibliotecas necessárias
import requests - (Só para acessar o link, porém se deixar o pdf baixado no repo não é necessário)
import pandas as pd - biblioteca de análise de dados de pandas para seu ambiente atual
import tabula – é um wrapper Python simples de tabula-java , que pode ler a tabela de PDF. Você pode ler tabelas de PDF e converter em DataFrame de pandas. tabula-py também permite converter um arquivo PDF em arquivo CSV/TSV/JSON.

2º Task - Consultar e baixar tabelas/planilhas que vamos consumir numa primeira versão
https://prograd.ufabc.edu.br/pdf/matriculas_deferidas_pos_ajuste_2022.3.pdf
https://prograd.ufabc.edu.br/pdf/ajuste_2022_3_turmas.xlsx
https://prograd.ufabc.edu.br/pdf/turmas_ingressantes_2022_3.pdf
https://prograd.ufabc.edu.br/pdf/reajuste_2022_3_matriculas_deferidas.pdf

5º Task  -  Tecnologias utilizadas:
1. Python(3.9)
2. Pandas
3. MongoDB
4. FastAPI

Problemas a serem discutidos:
•	Haverá um problema, no qual não sabemos quais matérias foram canceladas no Reajuste. Atualmente o colab vai somar as disciplinas do ajuste + as disciplinas pegadas no reajuste, não conseguindo diferenciar quais foram canceladas no reajuste. Podemos planejar para enviar uma solicitação para o SIC, para que assim conseguimos acessar a planilha com esses dados.
